"""add rotation and keyring tables

Revision ID: f24dfc0e6e7e
Revises: d1e2f3a4b5c6
Create Date: 2026-01-28 16:06:51.113874

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f24dfc0e6e7e'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rotation_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_kek_id', sa.String(length=64), nullable=False),
    sa.Column('cursor', sa.String(length=255), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secrets_keyring',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active_kek_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tga_logs')
    op.drop_table('tga_traces')
    op.drop_index(op.f('idx_a2a_frames_created_at'), table_name='a2a_frames')
    op.drop_index(op.f('idx_a2a_frames_recipient'), table_name='a2a_frames')
    op.drop_constraint(op.f('uq_frame_replay'), 'a2a_frames', type_='unique')
    op.create_index(op.f('ix_a2a_frames_created_at'), 'a2a_frames', ['created_at'], unique=False)
    op.create_index(op.f('ix_a2a_frames_recipient_id'), 'a2a_frames', ['recipient_id'], unique=False)
    op.drop_index(op.f('idx_a2a_groups_owner'), table_name='a2a_groups')
    op.drop_index(op.f('idx_a2a_sessions_initiator'), table_name='a2a_sessions')
    op.drop_index(op.f('idx_a2a_sessions_responder'), table_name='a2a_sessions')
    op.drop_index(op.f('idx_a2a_tasks_key_id'), table_name='a2a_tasks')
    op.drop_index(op.f('idx_a2a_tasks_org_id'), table_name='a2a_tasks')
    op.drop_index(op.f('idx_a2a_tasks_request_id'), table_name='a2a_tasks')
    op.create_index(op.f('ix_a2a_tasks_created_at'), 'a2a_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_key_id'), 'a2a_tasks', ['key_id'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_org_id'), 'a2a_tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_request_id'), 'a2a_tasks', ['request_id'], unique=False)
    op.create_index(op.f('ix_a2a_tasks_team_id'), 'a2a_tasks', ['team_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=True)
    op.drop_index(op.f('idx_reservations_expires'), table_name='budget_reservations')
    op.create_index(op.f('ix_budget_reservations_expires_at'), 'budget_reservations', ['expires_at'], unique=False)
    op.add_column('principals', sa.Column('public_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_principals_public_key'), 'principals', ['public_key'], unique=False)
    op.add_column('secrets', sa.Column('aad', sa.Text(), nullable=True))
    op.alter_column('secrets', 'nonce',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('secrets', 'tag',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_secrets_name'), table_name='secrets')
    op.drop_constraint(op.f('uq_secrets_name'), 'secrets', type_='unique')
    op.create_index(op.f('ix_secrets_key_id'), 'secrets', ['key_id'], unique=False)
    op.create_index(op.f('ix_secrets_name'), 'secrets', ['name'], unique=True)
    op.drop_constraint(op.f('uq_usage_event_request'), 'usage_events', type_='unique')
    op.create_index(op.f('ix_usage_events_request_id'), 'usage_events', ['request_id'], unique=True)
    op.drop_index(op.f('idx_usage_rollups_key'), table_name='usage_rollups_daily')
    op.drop_index(op.f('idx_usage_rollups_team'), table_name='usage_rollups_daily')
    op.create_index(op.f('ix_usage_rollups_daily_key_id'), 'usage_rollups_daily', ['key_id'], unique=False)
    op.create_index(op.f('ix_usage_rollups_daily_team_id'), 'usage_rollups_daily', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_rollups_daily_team_id'), table_name='usage_rollups_daily')
    op.drop_index(op.f('ix_usage_rollups_daily_key_id'), table_name='usage_rollups_daily')
    op.create_index(op.f('idx_usage_rollups_team'), 'usage_rollups_daily', ['team_id'], unique=False)
    op.create_index(op.f('idx_usage_rollups_key'), 'usage_rollups_daily', ['key_id'], unique=False)
    op.drop_index(op.f('ix_usage_events_request_id'), table_name='usage_events')
    op.create_unique_constraint(op.f('uq_usage_event_request'), 'usage_events', ['request_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_secrets_name'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_key_id'), table_name='secrets')
    op.create_unique_constraint(op.f('uq_secrets_name'), 'secrets', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_secrets_name'), 'secrets', ['name'], unique=False)
    op.alter_column('secrets', 'tag',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('secrets', 'nonce',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('secrets', 'aad')
    op.drop_index(op.f('ix_principals_public_key'), table_name='principals')
    op.drop_column('principals', 'public_key')
    op.drop_index(op.f('ix_budget_reservations_expires_at'), table_name='budget_reservations')
    op.create_index(op.f('idx_reservations_expires'), 'budget_reservations', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_a2a_tasks_team_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_request_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_org_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_key_id'), table_name='a2a_tasks')
    op.drop_index(op.f('ix_a2a_tasks_created_at'), table_name='a2a_tasks')
    op.create_index(op.f('idx_a2a_tasks_request_id'), 'a2a_tasks', ['request_id'], unique=False)
    op.create_index(op.f('idx_a2a_tasks_org_id'), 'a2a_tasks', ['org_id'], unique=False)
    op.create_index(op.f('idx_a2a_tasks_key_id'), 'a2a_tasks', ['key_id'], unique=False)
    op.create_index(op.f('idx_a2a_sessions_responder'), 'a2a_sessions', ['responder_id'], unique=False)
    op.create_index(op.f('idx_a2a_sessions_initiator'), 'a2a_sessions', ['initiator_id'], unique=False)
    op.create_index(op.f('idx_a2a_groups_owner'), 'a2a_groups', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_a2a_frames_recipient_id'), table_name='a2a_frames')
    op.drop_index(op.f('ix_a2a_frames_created_at'), table_name='a2a_frames')
    op.create_unique_constraint(op.f('uq_frame_replay'), 'a2a_frames', ['session_id', 'sender_id', 'sender_seq'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_a2a_frames_recipient'), 'a2a_frames', ['recipient_id'], unique=False)
    op.create_index(op.f('idx_a2a_frames_created_at'), 'a2a_frames', ['session_id', 'created_at', 'sender_id', 'sender_seq'], unique=False)
    op.create_table('tga_traces',
    sa.Column('trace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schema_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('schema_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_sequence_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_entry_digest', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_digest', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('trace_id', name='tga_traces_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tga_logs',
    sa.Column('trace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_digest', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prev_entry_digest', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ts', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artifact_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artifact_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artifact_digest', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_call_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artifact_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('schema_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['tga_traces.trace_id'], name=op.f('tga_logs_trace_id_fkey')),
    sa.PrimaryKeyConstraint('trace_id', 'sequence_number', name=op.f('tga_logs_pkey'))
    )
    op.drop_table('secrets_keyring')
    op.drop_table('rotation_operations')
    # ### end Alembic commands ###
